-- AHJ Agency Supabase setup
-- Run this in Supabase Dashboard > SQL Editor.

create table if not exists public.customer_inquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  email text,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.customer_inquiries enable row level security;

-- Allow the public website to submit new inquiries.
create policy "Public can submit customer inquiries"
on public.customer_inquiries
for insert
to anon
with check (
  char_length(name) between 1 and 150
  and char_length(phone) between 3 and 40
  and char_length(message) between 1 and 5000
);

-- Do NOT create a public SELECT policy.
-- Customer inquiries should only be read by authenticated/admin users.
